# Use the slim Python image as a base
FROM python:3.12-slim

# RUN apt update && apt \
#   && apt-get clean && rm -rf /var/lib/apt/lists/*


# Install dependencies
RUN  pip install --upgrade pip &&  pip install dbt-core dbt-bigquery