stock_modeling:
  outputs:
    dev:
      dataset: stock_data
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile:  /usr/app/config/stock-pipeline-dbt-cloud.json
      location: US
      method: service-account
      priority: interactive
      project: stock-pipeline-dbt-cloud
      threads: 1
      type: bigquery
  target: dev
