name: Docker Image CI

on:
  push:
    branches: [ "main", "ci/cd" ]
  pull_request:
    branches: [ "main", "ci/cd" ]

jobs:
  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0

  #     - name: Super-Linter
  #       uses: super-linter/super-linter/slim@v7.4.0
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    # needs: lint
    steps:
      - uses: actions/checkout@v4

      - name: Insure scripts are executable
        run: chmod +x scripts/airflow-init.sh
      
      - name: Set AIRFLOW_UID in .env
        run: |
          echo "AIRFLOW_UID=$(id -u)" > .env

      - name: Write config file from secret
        run: |
          mkdir -p config
          echo "${{ secrets.CONFIG_FILE_CONTENTS }}" > config/configuration.conf

      - name: Build and run Docker Compose
        run: docker compose up -d --build

      - name: Show Airflow Init Log on Failure
        if: failure()
        run: docker compose logs airflow-init

  pytest:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Run unit tests inside Airflow container
        run: docker exec airflow-scheduler bash -c "python -m pytest"