name: Docker Image CI

on:
  push:
    branches: [ "main", "ci/cd" ]
  pull_request:
    branches: [ "main", "ci/cd" ]

jobs:
<<<<<<< HEAD
<<<<<<< HEAD
  build-and-test:
=======
  build:
>>>>>>> 4e0e805 (refactor(ci.yml): Remove commented-out lint job from CI workflow)
=======
  build-and-test:
>>>>>>> 4bd19fd (ci(fix): build and tests in one job)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Insure scripts are executable
        run: chmod +x scripts/airflow-init.sh
      
      - name: Set AIRFLOW_UID in .env
        run: echo "AIRFLOW_UID=$(id -u)" > .env

      - name: Write config file from secret
        run: |
          mkdir -p config
          echo "${{ secrets.CONFIG_FILE_CONTENTS }}" > config/configuration.conf

      - name: Build and run Docker Compose
        run: docker compose up -d --build

      - name: Run unit tests inside Airflow container
        run: docker exec airflow-scheduler bash -c "python -m pytest"

      - name: Show Airflow Init Log on Failure
        if: failure()
        run: docker compose logs airflow-init