name: Docker Image CI

on:
  push:
    branches: [ "main", "ci/cd" ]
  pull_request:
    branches: [ "main", "ci/cd" ]

jobs:
  dbt-docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Create local config file 
      id: create-json
      uses: jsdaniell/create-json@v1.2.3
      with:
        name: "config/stock-pipeline-dbt-cloud.json"
        json: ${{ secrets.BIGQUERY_KEY_JSON }}

    - name: Validate BIGQUERY_KEY_JSON
      run: |
        python -c "import json,sys; json.load(open('config/stock-pipeline-dbt-cloud.json'))"
        
    - name: Build docker image
      run: docker build -t dbt-image -f Dockerfile.dbt .
    - name: Prepare dbt profile dir
      run: |
        mkdir -p .dbt
        cp profiles.yml .dbt/profiles.yml

    - name: Run dbt docs in Docker
      run: |
        docker run --rm \
          -v ${{ github.workspace }}/stock_modeling:/usr/app/stock_modeling \
          -v ${{ github.workspace }}/config:/usr/app/config \
          -v ${{ github.workspace }}/.dbt:/root/.dbt \
          dbt-image \
          dbt docs generate --project-dir /usr/app/stock_modeling

    - name: Deploy docs to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: stock_modeling/target
